[package]
name = "minotari"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["full"] }
lightweight_wallet_libs = { git = "https://github.com/tari-project/tari-wallet", rev = "83364a19642516036c87264344dbd3992d7bd039", features = [
    "http",
] }
# lightweight_wallet_libs = { path = "../tari-wallet", features = ["http"] }
clap = { version = "4.5.47", features = ["derive"] }
hex = "0.4.3"
chacha20poly1305 = { version = "0.10.1", features = ["rand_core", "std"] }
serde_json = "1.0.143"
sqlx = { version = "0.8.6", features = [
    "migrate",
    "runtime-tokio",
    "sqlite",
    "macros",
] }
blake2 = "0.10.6"
tari_crypto = { version = "0.22.1", features = ["borsh"] }
tari_utilities = { version = "0.8", features = ["std"] }
chrono = "0.4.42"
serde = "1.0.225"
tari_common_types = { git = "https://github.com/stringhandler/tari/", rev = "a39cb6520c6d58c0740f2df65770a4d01386a3c2" }
tari_transaction_components = { git = "https://github.com/stringhandler/tari/", rev = "a39cb6520c6d58c0740f2df65770a4d01386a3c2" }
